//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ZebraPruebas.WebServiceProducto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSPortalBinding", Namespace="urn:WSPortal")]
    public partial class WSPortal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarImagenProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarProductoClasificacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProductoEnsambleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarUnidadesMedidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTblSexoPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTblMaterialPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTblMarcaPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarProductosPorFiltroWebOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarEstadoProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarProductosPorClasificacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarProductosPorVectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarUbicacionProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ColoresPorProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PresentacionPorProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarProductoJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback BusquedaProductosCoincidenciasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImagenesProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSPortal() {
            this.Url = global::ZebraPruebas.Properties.Settings.Default.In_Moda_Fantasy_WebServiceProducto_WSPortal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarImagenProductoCompletedEventHandler ConsultarImagenProductoCompleted;
        
        /// <remarks/>
        public event ConsultarProductoCompletedEventHandler ConsultarProductoCompleted;
        
        /// <remarks/>
        public event ConsultarProductoClasificacionCompletedEventHandler ConsultarProductoClasificacionCompleted;
        
        /// <remarks/>
        public event ProductoCompletedEventHandler ProductoCompleted;
        
        /// <remarks/>
        public event ProductoEnsambleCompletedEventHandler ProductoEnsambleCompleted;
        
        /// <remarks/>
        public event ActualizarProductoCompletedEventHandler ActualizarProductoCompleted;
        
        /// <remarks/>
        public event ListarUnidadesMedidaCompletedEventHandler ListarUnidadesMedidaCompleted;
        
        /// <remarks/>
        public event ListarTblSexoPCompletedEventHandler ListarTblSexoPCompleted;
        
        /// <remarks/>
        public event ListarTblMaterialPCompletedEventHandler ListarTblMaterialPCompleted;
        
        /// <remarks/>
        public event ListarTblMarcaPCompletedEventHandler ListarTblMarcaPCompleted;
        
        /// <remarks/>
        public event ListarProductosCompletedEventHandler ListarProductosCompleted;
        
        /// <remarks/>
        public event ListarProductosPorFiltroWebCompletedEventHandler ListarProductosPorFiltroWebCompleted;
        
        /// <remarks/>
        public event ActualizarEstadoProductoCompletedEventHandler ActualizarEstadoProductoCompleted;
        
        /// <remarks/>
        public event ListarProductosPorClasificacionCompletedEventHandler ListarProductosPorClasificacionCompleted;
        
        /// <remarks/>
        public event ListarProductosPorVectorCompletedEventHandler ListarProductosPorVectorCompleted;
        
        /// <remarks/>
        public event ListarUbicacionProductosCompletedEventHandler ListarUbicacionProductosCompleted;
        
        /// <remarks/>
        public event ColoresPorProductoCompletedEventHandler ColoresPorProductoCompleted;
        
        /// <remarks/>
        public event PresentacionPorProductoCompletedEventHandler PresentacionPorProductoCompleted;
        
        /// <remarks/>
        public event ConsultarProductoJsonCompletedEventHandler ConsultarProductoJsonCompleted;
        
        /// <remarks/>
        public event BusquedaProductosCoincidenciasCompletedEventHandler BusquedaProductosCoincidenciasCompleted;
        
        /// <remarks/>
        public event ImagenesProductoCompletedEventHandler ImagenesProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/Consultar" +
            "ImagenProducto", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultarImagenProducto(string strReferencia) {
            object[] results = this.Invoke("ConsultarImagenProducto", new object[] {
                        strReferencia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarImagenProductoAsync(string strReferencia) {
            this.ConsultarImagenProductoAsync(strReferencia, null);
        }
        
        /// <remarks/>
        public void ConsultarImagenProductoAsync(string strReferencia, object userState) {
            if ((this.ConsultarImagenProductoOperationCompleted == null)) {
                this.ConsultarImagenProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarImagenProductoOperationCompleted);
            }
            this.InvokeAsync("ConsultarImagenProducto", new object[] {
                        strReferencia}, this.ConsultarImagenProductoOperationCompleted, userState);
        }
        
        private void OnConsultarImagenProductoOperationCompleted(object arg) {
            if ((this.ConsultarImagenProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarImagenProductoCompleted(this, new ConsultarImagenProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/Consultar" +
            "Producto", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultarProducto(string strReferencia, string intPrecio) {
            object[] results = this.Invoke("ConsultarProducto", new object[] {
                        strReferencia,
                        intPrecio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarProductoAsync(string strReferencia, string intPrecio) {
            this.ConsultarProductoAsync(strReferencia, intPrecio, null);
        }
        
        /// <remarks/>
        public void ConsultarProductoAsync(string strReferencia, string intPrecio, object userState) {
            if ((this.ConsultarProductoOperationCompleted == null)) {
                this.ConsultarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarProductoOperationCompleted);
            }
            this.InvokeAsync("ConsultarProducto", new object[] {
                        strReferencia,
                        intPrecio}, this.ConsultarProductoOperationCompleted, userState);
        }
        
        private void OnConsultarProductoOperationCompleted(object arg) {
            if ((this.ConsultarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarProductoCompleted(this, new ConsultarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/Consultar" +
            "ProductoClasificacion", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultarProductoClasificacion(string strClase, string strLinea, string strGrupo, string strTipo, string strWhere, string strRangoPrecio, string intPrecio, string intStart, string intEnd) {
            object[] results = this.Invoke("ConsultarProductoClasificacion", new object[] {
                        strClase,
                        strLinea,
                        strGrupo,
                        strTipo,
                        strWhere,
                        strRangoPrecio,
                        intPrecio,
                        intStart,
                        intEnd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarProductoClasificacionAsync(string strClase, string strLinea, string strGrupo, string strTipo, string strWhere, string strRangoPrecio, string intPrecio, string intStart, string intEnd) {
            this.ConsultarProductoClasificacionAsync(strClase, strLinea, strGrupo, strTipo, strWhere, strRangoPrecio, intPrecio, intStart, intEnd, null);
        }
        
        /// <remarks/>
        public void ConsultarProductoClasificacionAsync(string strClase, string strLinea, string strGrupo, string strTipo, string strWhere, string strRangoPrecio, string intPrecio, string intStart, string intEnd, object userState) {
            if ((this.ConsultarProductoClasificacionOperationCompleted == null)) {
                this.ConsultarProductoClasificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarProductoClasificacionOperationCompleted);
            }
            this.InvokeAsync("ConsultarProductoClasificacion", new object[] {
                        strClase,
                        strLinea,
                        strGrupo,
                        strTipo,
                        strWhere,
                        strRangoPrecio,
                        intPrecio,
                        intStart,
                        intEnd}, this.ConsultarProductoClasificacionOperationCompleted, userState);
        }
        
        private void OnConsultarProductoClasificacionOperationCompleted(object arg) {
            if ((this.ConsultarProductoClasificacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarProductoClasificacionCompleted(this, new ConsultarProductoClasificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/Producto", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Producto(string strReferencia) {
            object[] results = this.Invoke("Producto", new object[] {
                        strReferencia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProductoAsync(string strReferencia) {
            this.ProductoAsync(strReferencia, null);
        }
        
        /// <remarks/>
        public void ProductoAsync(string strReferencia, object userState) {
            if ((this.ProductoOperationCompleted == null)) {
                this.ProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductoOperationCompleted);
            }
            this.InvokeAsync("Producto", new object[] {
                        strReferencia}, this.ProductoOperationCompleted, userState);
        }
        
        private void OnProductoOperationCompleted(object arg) {
            if ((this.ProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductoCompleted(this, new ProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ProductoE" +
            "nsamble", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ProductoEnsamble(string strReferencia) {
            object[] results = this.Invoke("ProductoEnsamble", new object[] {
                        strReferencia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProductoEnsambleAsync(string strReferencia) {
            this.ProductoEnsambleAsync(strReferencia, null);
        }
        
        /// <remarks/>
        public void ProductoEnsambleAsync(string strReferencia, object userState) {
            if ((this.ProductoEnsambleOperationCompleted == null)) {
                this.ProductoEnsambleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductoEnsambleOperationCompleted);
            }
            this.InvokeAsync("ProductoEnsamble", new object[] {
                        strReferencia}, this.ProductoEnsambleOperationCompleted, userState);
        }
        
        private void OnProductoEnsambleOperationCompleted(object arg) {
            if ((this.ProductoEnsambleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductoEnsambleCompleted(this, new ProductoEnsambleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/Actualiza" +
            "rProducto", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ActualizarProducto(
                    string strReferencia, 
                    string intPrecio1, 
                    string intPrecio2, 
                    string intPrecio3, 
                    string intPrecio4, 
                    string intPrecio5, 
                    string strDescripcion, 
                    string strUdm, 
                    string intCantidad, 
                    string strDimension, 
                    string strMaterial, 
                    string intCantXpaca, 
                    string strUbicacion, 
                    string strObservacion, 
                    string strSexo, 
                    string strMaterialP, 
                    string strMarca) {
            object[] results = this.Invoke("ActualizarProducto", new object[] {
                        strReferencia,
                        intPrecio1,
                        intPrecio2,
                        intPrecio3,
                        intPrecio4,
                        intPrecio5,
                        strDescripcion,
                        strUdm,
                        intCantidad,
                        strDimension,
                        strMaterial,
                        intCantXpaca,
                        strUbicacion,
                        strObservacion,
                        strSexo,
                        strMaterialP,
                        strMarca});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarProductoAsync(
                    string strReferencia, 
                    string intPrecio1, 
                    string intPrecio2, 
                    string intPrecio3, 
                    string intPrecio4, 
                    string intPrecio5, 
                    string strDescripcion, 
                    string strUdm, 
                    string intCantidad, 
                    string strDimension, 
                    string strMaterial, 
                    string intCantXpaca, 
                    string strUbicacion, 
                    string strObservacion, 
                    string strSexo, 
                    string strMaterialP, 
                    string strMarca) {
            this.ActualizarProductoAsync(strReferencia, intPrecio1, intPrecio2, intPrecio3, intPrecio4, intPrecio5, strDescripcion, strUdm, intCantidad, strDimension, strMaterial, intCantXpaca, strUbicacion, strObservacion, strSexo, strMaterialP, strMarca, null);
        }
        
        /// <remarks/>
        public void ActualizarProductoAsync(
                    string strReferencia, 
                    string intPrecio1, 
                    string intPrecio2, 
                    string intPrecio3, 
                    string intPrecio4, 
                    string intPrecio5, 
                    string strDescripcion, 
                    string strUdm, 
                    string intCantidad, 
                    string strDimension, 
                    string strMaterial, 
                    string intCantXpaca, 
                    string strUbicacion, 
                    string strObservacion, 
                    string strSexo, 
                    string strMaterialP, 
                    string strMarca, 
                    object userState) {
            if ((this.ActualizarProductoOperationCompleted == null)) {
                this.ActualizarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarProductoOperationCompleted);
            }
            this.InvokeAsync("ActualizarProducto", new object[] {
                        strReferencia,
                        intPrecio1,
                        intPrecio2,
                        intPrecio3,
                        intPrecio4,
                        intPrecio5,
                        strDescripcion,
                        strUdm,
                        intCantidad,
                        strDimension,
                        strMaterial,
                        intCantXpaca,
                        strUbicacion,
                        strObservacion,
                        strSexo,
                        strMaterialP,
                        strMarca}, this.ActualizarProductoOperationCompleted, userState);
        }
        
        private void OnActualizarProductoOperationCompleted(object arg) {
            if ((this.ActualizarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarProductoCompleted(this, new ActualizarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ListarUni" +
            "dadesMedida", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ListarUnidadesMedida() {
            object[] results = this.Invoke("ListarUnidadesMedida", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarUnidadesMedidaAsync() {
            this.ListarUnidadesMedidaAsync(null);
        }
        
        /// <remarks/>
        public void ListarUnidadesMedidaAsync(object userState) {
            if ((this.ListarUnidadesMedidaOperationCompleted == null)) {
                this.ListarUnidadesMedidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarUnidadesMedidaOperationCompleted);
            }
            this.InvokeAsync("ListarUnidadesMedida", new object[0], this.ListarUnidadesMedidaOperationCompleted, userState);
        }
        
        private void OnListarUnidadesMedidaOperationCompleted(object arg) {
            if ((this.ListarUnidadesMedidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarUnidadesMedidaCompleted(this, new ListarUnidadesMedidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ListarTbl" +
            "SexoP", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ListarTblSexoP() {
            object[] results = this.Invoke("ListarTblSexoP", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarTblSexoPAsync() {
            this.ListarTblSexoPAsync(null);
        }
        
        /// <remarks/>
        public void ListarTblSexoPAsync(object userState) {
            if ((this.ListarTblSexoPOperationCompleted == null)) {
                this.ListarTblSexoPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTblSexoPOperationCompleted);
            }
            this.InvokeAsync("ListarTblSexoP", new object[0], this.ListarTblSexoPOperationCompleted, userState);
        }
        
        private void OnListarTblSexoPOperationCompleted(object arg) {
            if ((this.ListarTblSexoPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTblSexoPCompleted(this, new ListarTblSexoPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ListarTbl" +
            "MaterialP", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ListarTblMaterialP() {
            object[] results = this.Invoke("ListarTblMaterialP", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarTblMaterialPAsync() {
            this.ListarTblMaterialPAsync(null);
        }
        
        /// <remarks/>
        public void ListarTblMaterialPAsync(object userState) {
            if ((this.ListarTblMaterialPOperationCompleted == null)) {
                this.ListarTblMaterialPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTblMaterialPOperationCompleted);
            }
            this.InvokeAsync("ListarTblMaterialP", new object[0], this.ListarTblMaterialPOperationCompleted, userState);
        }
        
        private void OnListarTblMaterialPOperationCompleted(object arg) {
            if ((this.ListarTblMaterialPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTblMaterialPCompleted(this, new ListarTblMaterialPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ListarTbl" +
            "MarcaP", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ListarTblMarcaP() {
            object[] results = this.Invoke("ListarTblMarcaP", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarTblMarcaPAsync() {
            this.ListarTblMarcaPAsync(null);
        }
        
        /// <remarks/>
        public void ListarTblMarcaPAsync(object userState) {
            if ((this.ListarTblMarcaPOperationCompleted == null)) {
                this.ListarTblMarcaPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTblMarcaPOperationCompleted);
            }
            this.InvokeAsync("ListarTblMarcaP", new object[0], this.ListarTblMarcaPOperationCompleted, userState);
        }
        
        private void OnListarTblMarcaPOperationCompleted(object arg) {
            if ((this.ListarTblMarcaPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTblMarcaPCompleted(this, new ListarTblMarcaPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ListarPro" +
            "ductos", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ListarProductos() {
            object[] results = this.Invoke("ListarProductos", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarProductosAsync() {
            this.ListarProductosAsync(null);
        }
        
        /// <remarks/>
        public void ListarProductosAsync(object userState) {
            if ((this.ListarProductosOperationCompleted == null)) {
                this.ListarProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarProductosOperationCompleted);
            }
            this.InvokeAsync("ListarProductos", new object[0], this.ListarProductosOperationCompleted, userState);
        }
        
        private void OnListarProductosOperationCompleted(object arg) {
            if ((this.ListarProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarProductosCompleted(this, new ListarProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ListarPro" +
            "ductosPorFiltroWeb", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ListarProductosPorFiltroWeb(string strRgMinPrecio, string strRgMaxPrecio, string strPalabraClave, string strClase, string strPrecio, string strRgMaxPaginacion, string strRgMinPaginacion) {
            object[] results = this.Invoke("ListarProductosPorFiltroWeb", new object[] {
                        strRgMinPrecio,
                        strRgMaxPrecio,
                        strPalabraClave,
                        strClase,
                        strPrecio,
                        strRgMaxPaginacion,
                        strRgMinPaginacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarProductosPorFiltroWebAsync(string strRgMinPrecio, string strRgMaxPrecio, string strPalabraClave, string strClase, string strPrecio, string strRgMaxPaginacion, string strRgMinPaginacion) {
            this.ListarProductosPorFiltroWebAsync(strRgMinPrecio, strRgMaxPrecio, strPalabraClave, strClase, strPrecio, strRgMaxPaginacion, strRgMinPaginacion, null);
        }
        
        /// <remarks/>
        public void ListarProductosPorFiltroWebAsync(string strRgMinPrecio, string strRgMaxPrecio, string strPalabraClave, string strClase, string strPrecio, string strRgMaxPaginacion, string strRgMinPaginacion, object userState) {
            if ((this.ListarProductosPorFiltroWebOperationCompleted == null)) {
                this.ListarProductosPorFiltroWebOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarProductosPorFiltroWebOperationCompleted);
            }
            this.InvokeAsync("ListarProductosPorFiltroWeb", new object[] {
                        strRgMinPrecio,
                        strRgMaxPrecio,
                        strPalabraClave,
                        strClase,
                        strPrecio,
                        strRgMaxPaginacion,
                        strRgMinPaginacion}, this.ListarProductosPorFiltroWebOperationCompleted, userState);
        }
        
        private void OnListarProductosPorFiltroWebOperationCompleted(object arg) {
            if ((this.ListarProductosPorFiltroWebCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarProductosPorFiltroWebCompleted(this, new ListarProductosPorFiltroWebCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/Actualiza" +
            "rEstadoProducto", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ActualizarEstadoProducto(string strReferencia, string intEstado) {
            object[] results = this.Invoke("ActualizarEstadoProducto", new object[] {
                        strReferencia,
                        intEstado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarEstadoProductoAsync(string strReferencia, string intEstado) {
            this.ActualizarEstadoProductoAsync(strReferencia, intEstado, null);
        }
        
        /// <remarks/>
        public void ActualizarEstadoProductoAsync(string strReferencia, string intEstado, object userState) {
            if ((this.ActualizarEstadoProductoOperationCompleted == null)) {
                this.ActualizarEstadoProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarEstadoProductoOperationCompleted);
            }
            this.InvokeAsync("ActualizarEstadoProducto", new object[] {
                        strReferencia,
                        intEstado}, this.ActualizarEstadoProductoOperationCompleted, userState);
        }
        
        private void OnActualizarEstadoProductoOperationCompleted(object arg) {
            if ((this.ActualizarEstadoProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarEstadoProductoCompleted(this, new ActualizarEstadoProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ListarPro" +
            "ductosPorClasificacion", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ListarProductosPorClasificacion(string strClase, string strLinea, string strGrupo, string strTipo) {
            object[] results = this.Invoke("ListarProductosPorClasificacion", new object[] {
                        strClase,
                        strLinea,
                        strGrupo,
                        strTipo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarProductosPorClasificacionAsync(string strClase, string strLinea, string strGrupo, string strTipo) {
            this.ListarProductosPorClasificacionAsync(strClase, strLinea, strGrupo, strTipo, null);
        }
        
        /// <remarks/>
        public void ListarProductosPorClasificacionAsync(string strClase, string strLinea, string strGrupo, string strTipo, object userState) {
            if ((this.ListarProductosPorClasificacionOperationCompleted == null)) {
                this.ListarProductosPorClasificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarProductosPorClasificacionOperationCompleted);
            }
            this.InvokeAsync("ListarProductosPorClasificacion", new object[] {
                        strClase,
                        strLinea,
                        strGrupo,
                        strTipo}, this.ListarProductosPorClasificacionOperationCompleted, userState);
        }
        
        private void OnListarProductosPorClasificacionOperationCompleted(object arg) {
            if ((this.ListarProductosPorClasificacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarProductosPorClasificacionCompleted(this, new ListarProductosPorClasificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ListarPro" +
            "ductosPorVector", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ListarProductosPorVector(string strProductos) {
            object[] results = this.Invoke("ListarProductosPorVector", new object[] {
                        strProductos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarProductosPorVectorAsync(string strProductos) {
            this.ListarProductosPorVectorAsync(strProductos, null);
        }
        
        /// <remarks/>
        public void ListarProductosPorVectorAsync(string strProductos, object userState) {
            if ((this.ListarProductosPorVectorOperationCompleted == null)) {
                this.ListarProductosPorVectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarProductosPorVectorOperationCompleted);
            }
            this.InvokeAsync("ListarProductosPorVector", new object[] {
                        strProductos}, this.ListarProductosPorVectorOperationCompleted, userState);
        }
        
        private void OnListarProductosPorVectorOperationCompleted(object arg) {
            if ((this.ListarProductosPorVectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarProductosPorVectorCompleted(this, new ListarProductosPorVectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ListarUbi" +
            "cacionProductos", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ListarUbicacionProductos(string strProductos) {
            object[] results = this.Invoke("ListarUbicacionProductos", new object[] {
                        strProductos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarUbicacionProductosAsync(string strProductos) {
            this.ListarUbicacionProductosAsync(strProductos, null);
        }
        
        /// <remarks/>
        public void ListarUbicacionProductosAsync(string strProductos, object userState) {
            if ((this.ListarUbicacionProductosOperationCompleted == null)) {
                this.ListarUbicacionProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarUbicacionProductosOperationCompleted);
            }
            this.InvokeAsync("ListarUbicacionProductos", new object[] {
                        strProductos}, this.ListarUbicacionProductosOperationCompleted, userState);
        }
        
        private void OnListarUbicacionProductosOperationCompleted(object arg) {
            if ((this.ListarUbicacionProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarUbicacionProductosCompleted(this, new ListarUbicacionProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ColoresPo" +
            "rProducto", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ColoresPorProducto(string strIdProducto) {
            object[] results = this.Invoke("ColoresPorProducto", new object[] {
                        strIdProducto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ColoresPorProductoAsync(string strIdProducto) {
            this.ColoresPorProductoAsync(strIdProducto, null);
        }
        
        /// <remarks/>
        public void ColoresPorProductoAsync(string strIdProducto, object userState) {
            if ((this.ColoresPorProductoOperationCompleted == null)) {
                this.ColoresPorProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnColoresPorProductoOperationCompleted);
            }
            this.InvokeAsync("ColoresPorProducto", new object[] {
                        strIdProducto}, this.ColoresPorProductoOperationCompleted, userState);
        }
        
        private void OnColoresPorProductoOperationCompleted(object arg) {
            if ((this.ColoresPorProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ColoresPorProductoCompleted(this, new ColoresPorProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/Presentac" +
            "ionPorProducto", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string PresentacionPorProducto(string strIdProducto) {
            object[] results = this.Invoke("PresentacionPorProducto", new object[] {
                        strIdProducto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PresentacionPorProductoAsync(string strIdProducto) {
            this.PresentacionPorProductoAsync(strIdProducto, null);
        }
        
        /// <remarks/>
        public void PresentacionPorProductoAsync(string strIdProducto, object userState) {
            if ((this.PresentacionPorProductoOperationCompleted == null)) {
                this.PresentacionPorProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPresentacionPorProductoOperationCompleted);
            }
            this.InvokeAsync("PresentacionPorProducto", new object[] {
                        strIdProducto}, this.PresentacionPorProductoOperationCompleted, userState);
        }
        
        private void OnPresentacionPorProductoOperationCompleted(object arg) {
            if ((this.PresentacionPorProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PresentacionPorProductoCompleted(this, new PresentacionPorProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/Consultar" +
            "ProductoJson", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultarProductoJson(string strReferencia) {
            object[] results = this.Invoke("ConsultarProductoJson", new object[] {
                        strReferencia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarProductoJsonAsync(string strReferencia) {
            this.ConsultarProductoJsonAsync(strReferencia, null);
        }
        
        /// <remarks/>
        public void ConsultarProductoJsonAsync(string strReferencia, object userState) {
            if ((this.ConsultarProductoJsonOperationCompleted == null)) {
                this.ConsultarProductoJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarProductoJsonOperationCompleted);
            }
            this.InvokeAsync("ConsultarProductoJson", new object[] {
                        strReferencia}, this.ConsultarProductoJsonOperationCompleted, userState);
        }
        
        private void OnConsultarProductoJsonOperationCompleted(object arg) {
            if ((this.ConsultarProductoJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarProductoJsonCompleted(this, new ConsultarProductoJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/BusquedaP" +
            "roductosCoincidencias", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string BusquedaProductosCoincidencias(string strReferencia, string intNroResultados) {
            object[] results = this.Invoke("BusquedaProductosCoincidencias", new object[] {
                        strReferencia,
                        intNroResultados});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BusquedaProductosCoincidenciasAsync(string strReferencia, string intNroResultados) {
            this.BusquedaProductosCoincidenciasAsync(strReferencia, intNroResultados, null);
        }
        
        /// <remarks/>
        public void BusquedaProductosCoincidenciasAsync(string strReferencia, string intNroResultados, object userState) {
            if ((this.BusquedaProductosCoincidenciasOperationCompleted == null)) {
                this.BusquedaProductosCoincidenciasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBusquedaProductosCoincidenciasOperationCompleted);
            }
            this.InvokeAsync("BusquedaProductosCoincidencias", new object[] {
                        strReferencia,
                        intNroResultados}, this.BusquedaProductosCoincidenciasOperationCompleted, userState);
        }
        
        private void OnBusquedaProductosCoincidenciasOperationCompleted(object arg) {
            if ((this.BusquedaProductosCoincidenciasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BusquedaProductosCoincidenciasCompleted(this, new BusquedaProductosCoincidenciasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://10.10.10.128/webserviceportal/WebService/WebServiceProductos.php/ImagenesP" +
            "roducto", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ImagenesProducto(string strReferencia) {
            object[] results = this.Invoke("ImagenesProducto", new object[] {
                        strReferencia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImagenesProductoAsync(string strReferencia) {
            this.ImagenesProductoAsync(strReferencia, null);
        }
        
        /// <remarks/>
        public void ImagenesProductoAsync(string strReferencia, object userState) {
            if ((this.ImagenesProductoOperationCompleted == null)) {
                this.ImagenesProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImagenesProductoOperationCompleted);
            }
            this.InvokeAsync("ImagenesProducto", new object[] {
                        strReferencia}, this.ImagenesProductoOperationCompleted, userState);
        }
        
        private void OnImagenesProductoOperationCompleted(object arg) {
            if ((this.ImagenesProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImagenesProductoCompleted(this, new ImagenesProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarImagenProductoCompletedEventHandler(object sender, ConsultarImagenProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarImagenProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarImagenProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarProductoCompletedEventHandler(object sender, ConsultarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarProductoClasificacionCompletedEventHandler(object sender, ConsultarProductoClasificacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarProductoClasificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarProductoClasificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ProductoCompletedEventHandler(object sender, ProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ProductoEnsambleCompletedEventHandler(object sender, ProductoEnsambleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductoEnsambleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductoEnsambleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ActualizarProductoCompletedEventHandler(object sender, ActualizarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarUnidadesMedidaCompletedEventHandler(object sender, ListarUnidadesMedidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarUnidadesMedidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarUnidadesMedidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarTblSexoPCompletedEventHandler(object sender, ListarTblSexoPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTblSexoPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTblSexoPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarTblMaterialPCompletedEventHandler(object sender, ListarTblMaterialPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTblMaterialPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTblMaterialPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarTblMarcaPCompletedEventHandler(object sender, ListarTblMarcaPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTblMarcaPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTblMarcaPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarProductosCompletedEventHandler(object sender, ListarProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarProductosPorFiltroWebCompletedEventHandler(object sender, ListarProductosPorFiltroWebCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarProductosPorFiltroWebCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarProductosPorFiltroWebCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ActualizarEstadoProductoCompletedEventHandler(object sender, ActualizarEstadoProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarEstadoProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarEstadoProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarProductosPorClasificacionCompletedEventHandler(object sender, ListarProductosPorClasificacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarProductosPorClasificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarProductosPorClasificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarProductosPorVectorCompletedEventHandler(object sender, ListarProductosPorVectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarProductosPorVectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarProductosPorVectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ListarUbicacionProductosCompletedEventHandler(object sender, ListarUbicacionProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarUbicacionProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarUbicacionProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ColoresPorProductoCompletedEventHandler(object sender, ColoresPorProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ColoresPorProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ColoresPorProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PresentacionPorProductoCompletedEventHandler(object sender, PresentacionPorProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PresentacionPorProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PresentacionPorProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ConsultarProductoJsonCompletedEventHandler(object sender, ConsultarProductoJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarProductoJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarProductoJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BusquedaProductosCoincidenciasCompletedEventHandler(object sender, BusquedaProductosCoincidenciasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BusquedaProductosCoincidenciasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BusquedaProductosCoincidenciasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ImagenesProductoCompletedEventHandler(object sender, ImagenesProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImagenesProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImagenesProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591